using DyeHouseERP.Application.Checks.DTOs;
using DyeHouseERP.Application.Checks.Queries;
using DyeHouseERP.Application.Common.Exceptions;
using DyeHouseERP.Application.Common.Interfaces;
using DyeHouseERP.Domain.Entities;
using DyeHouseERP.Domain.Enums;
using DyeHouseERP.Domain.Exceptions;
using FluentValidation;
using MediatR;
using Microsoft.EntityFrameworkCore;

namespace DyeHouseERP.Application.Checks.Commands;

/// <summary>
/// Registers an incoming customer check (spec section 37 "Incoming Customer Checks").
/// The check number is the bank's own number - it is not generated by this system,
/// but it is checked for duplicates within the same bank/customer so the same
/// instrument can never be registered twice.
/// </summary>
public record RegisterCustomerCheckCommand(
    string CheckNumber, string BankName, decimal Amount,
    DateTime IssueDate, DateTime DueDate, string Issuer, Guid CustomerId,
    string Currency = "EGP", string? BranchName = null, string? CustomerReference = null,
    string? Notes = null, bool ConfirmInHandNow = true, DateTime? ReceivedDate = null)
    : IRequest<CheckDto>;

public class RegisterCustomerCheckCommandValidator : AbstractValidator<RegisterCustomerCheckCommand>
{
    public RegisterCustomerCheckCommandValidator()
    {
        RuleFor(x => x.CheckNumber).NotEmpty().MaximumLength(50);
        RuleFor(x => x.BankName).NotEmpty().MaximumLength(200);
        RuleFor(x => x.Issuer).NotEmpty().MaximumLength(200);
        RuleFor(x => x.Amount).GreaterThan(0);
        RuleFor(x => x.CustomerId).NotEmpty();
    }
}

public class RegisterCustomerCheckCommandHandler : IRequestHandler<RegisterCustomerCheckCommand, CheckDto>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    public RegisterCustomerCheckCommandHandler(IApplicationDbContext db, ICurrentUserService currentUser)
    { _db = db; _currentUser = currentUser; }

    public async Task<CheckDto> Handle(RegisterCustomerCheckCommand request, CancellationToken cancellationToken)
    {
        var customer = await _db.Customers.AsNoTracking()
            .FirstOrDefaultAsync(c => c.Id == request.CustomerId, cancellationToken)
            ?? throw new NotFoundException("Customer", request.CustomerId);

        await CheckRules.EnsureNotDuplicateAsync(_db, request.BankName, request.CheckNumber, request.CustomerId, null, cancellationToken);

        var entity = new Check(
            request.CheckNumber, CheckDirection.CustomerCheck, request.BankName, request.Amount,
            request.IssueDate, request.DueDate, request.Issuer, customer.Name, CheckHolderType.Customer,
            _currentUser.UserName, request.BranchName, request.Currency, request.CustomerReference,
            request.Notes, customerId: customer.Id);

        if (request.ConfirmInHandNow)
        {
            var company = await CheckRules.ResolveCompanyHolderNameAsync(_db, cancellationToken);
            entity.ConfirmReceipt(request.ReceivedDate ?? request.IssueDate, company, _currentUser.UserName);
        }

        _db.Checks.Add(entity);
        await _db.SaveChangesAsync(cancellationToken);

        var list = await CheckDtoBuilder.BuildManyAsync(_db, new List<Check> { entity }, true, cancellationToken);
        return list[0];
    }
}

/// <summary>
/// Registers an outgoing supplier check (spec section 37 "Outgoing Supplier Checks").
/// Issued by the company, so the original holder is the company itself and the
/// bank account it is drawn on is recorded for the cash effect when it clears.
/// </summary>
public record RegisterSupplierCheckCommand(
    string CheckNumber, string BankName, decimal Amount,
    DateTime IssueDate, DateTime DueDate, string Issuer, Guid SupplierId,
    Guid? TreasuryAccountId = null, string Currency = "EGP", string? BranchName = null,
    string? Notes = null, bool HandOverNow = false, DateTime? HandOverDate = null, string? Reason = null)
    : IRequest<CheckDto>;

public class RegisterSupplierCheckCommandValidator : AbstractValidator<RegisterSupplierCheckCommand>
{
    public RegisterSupplierCheckCommandValidator()
    {
        RuleFor(x => x.CheckNumber).NotEmpty().MaximumLength(50);
        RuleFor(x => x.BankName).NotEmpty().MaximumLength(200);
        RuleFor(x => x.Issuer).NotEmpty().MaximumLength(200);
        RuleFor(x => x.Amount).GreaterThan(0);
        RuleFor(x => x.SupplierId).NotEmpty();
    }
}

public class RegisterSupplierCheckCommandHandler : IRequestHandler<RegisterSupplierCheckCommand, CheckDto>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    public RegisterSupplierCheckCommandHandler(IApplicationDbContext db, ICurrentUserService currentUser)
    { _db = db; _currentUser = currentUser; }

    public async Task<CheckDto> Handle(RegisterSupplierCheckCommand request, CancellationToken cancellationToken)
    {
        var supplier = await _db.Suppliers.AsNoTracking()
            .FirstOrDefaultAsync(s => s.Id == request.SupplierId, cancellationToken)
            ?? throw new NotFoundException("Supplier", request.SupplierId);

        await CheckRules.EnsureNotDuplicateAsync(_db, request.BankName, request.CheckNumber, null, request.SupplierId, cancellationToken);

        var company = await CheckRules.ResolveCompanyHolderNameAsync(_db, cancellationToken);

        var entity = new Check(
            request.CheckNumber, CheckDirection.SupplierCheck, request.BankName, request.Amount,
            request.IssueDate, request.DueDate, request.Issuer, company, CheckHolderType.Company,
            _currentUser.UserName, request.BranchName, request.Currency, customerReference: null,
            notes: request.Notes, customerId: null, supplierId: supplier.Id);

        if (request.TreasuryAccountId.HasValue)
        {
            var accountExists = await _db.TreasuryAccounts.AsNoTracking()
                .AnyAsync(a => a.Id == request.TreasuryAccountId.Value, cancellationToken);
            if (!accountExists) throw new NotFoundException("Treasury Account", request.TreasuryAccountId.Value);

            // The account an outgoing check is drawn on is recorded for the cash effect -
            // it is not a "deposit", and it never changes who holds the instrument.
            entity.SetDrawnOnAccount(request.TreasuryAccountId.Value);
        }

        if (request.HandOverNow)
        {
            entity.EndorseToSupplier(supplier.Id, supplier.Name, request.HandOverDate ?? request.IssueDate,
                _currentUser.UserName, request.Reason);
        }

        _db.Checks.Add(entity);
        await _db.SaveChangesAsync(cancellationToken);

        var list = await CheckDtoBuilder.BuildManyAsync(_db, new List<Check> { entity }, true, cancellationToken);
        return list[0];
    }
}

/// <summary>Confirms a customer check is physically in the company's hands (Received -&gt; In Hand).</summary>
public record ConfirmCheckReceiptCommand(Guid Id, DateTime? MovementDate = null) : IRequest<CheckDto>;

public class ConfirmCheckReceiptCommandHandler : IRequestHandler<ConfirmCheckReceiptCommand, CheckDto>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    public ConfirmCheckReceiptCommandHandler(IApplicationDbContext db, ICurrentUserService currentUser)
    { _db = db; _currentUser = currentUser; }

    public async Task<CheckDto> Handle(ConfirmCheckReceiptCommand request, CancellationToken cancellationToken)
    {
        var company = await CheckRules.ResolveCompanyHolderNameAsync(_db, cancellationToken);
        return await CheckWorkflow.MutateAsync(_db, request.Id,
            entity => entity.ConfirmReceipt(request.MovementDate ?? DateTime.UtcNow, company, _currentUser.UserName),
            cancellationToken);
    }
}

/// <summary>
/// Endorses/transfers the SAME instrument to a supplier (spec section 39: Customer -&gt; Company -&gt; Supplier).
/// No new check row, no new cash: the holder changes and a movement is appended.
/// </summary>
public record EndorseCheckToSupplierCommand(
    Guid Id, Guid SupplierId, DateTime MovementDate, string? Reason = null, DateTime? DueDate = null)
    : IRequest<CheckDto>;

public class EndorseCheckToSupplierCommandValidator : AbstractValidator<EndorseCheckToSupplierCommand>
{
    public EndorseCheckToSupplierCommandValidator()
    {
        RuleFor(x => x.Id).NotEmpty();
        RuleFor(x => x.SupplierId).NotEmpty();
    }
}

public class EndorseCheckToSupplierCommandHandler : IRequestHandler<EndorseCheckToSupplierCommand, CheckDto>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    public EndorseCheckToSupplierCommandHandler(IApplicationDbContext db, ICurrentUserService currentUser)
    { _db = db; _currentUser = currentUser; }

    public async Task<CheckDto> Handle(EndorseCheckToSupplierCommand request, CancellationToken cancellationToken)
    {
        var supplier = await _db.Suppliers.AsNoTracking()
            .FirstOrDefaultAsync(s => s.Id == request.SupplierId, cancellationToken)
            ?? throw new NotFoundException("Supplier", request.SupplierId);

        return await CheckWorkflow.MutateAsync(_db, request.Id,
            entity => entity.EndorseToSupplier(supplier.Id, supplier.Name, request.MovementDate,
                _currentUser.UserName, request.Reason),
            cancellationToken);
    }
}

/// <summary>Deposits a check into a bank account. The cash effect is posted when the check actually clears (see ClearCheckCommand).</summary>
public record DepositCheckCommand(Guid Id, Guid TreasuryAccountId, DateTime? MovementDate = null, string? Notes = null)
    : IRequest<CheckDto>;

public class DepositCheckCommandHandler : IRequestHandler<DepositCheckCommand, CheckDto>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    public DepositCheckCommandHandler(IApplicationDbContext db, ICurrentUserService currentUser)
    { _db = db; _currentUser = currentUser; }

    public async Task<CheckDto> Handle(DepositCheckCommand request, CancellationToken cancellationToken)
    {
        var account = await _db.TreasuryAccounts.AsNoTracking()
            .FirstOrDefaultAsync(a => a.Id == request.TreasuryAccountId, cancellationToken)
            ?? throw new NotFoundException("Treasury Account", request.TreasuryAccountId);

        return await CheckWorkflow.MutateAsync(_db, request.Id,
            entity => entity.Deposit(account.Id, account.Name, request.MovementDate ?? DateTime.UtcNow,
                _currentUser.UserName, request.Notes),
            cancellationToken);
    }
}

/// <summary>
/// Marks a deposited check as cleared and posts the real cash/bank movement to the treasury
/// ledger (spec section 40: checks integrate with treasury, banks and accounting).
/// A cleared customer check increases the bank account; a cleared outgoing supplier check
/// decreases it. Nothing is ever posted twice: only this transition posts money.
/// </summary>
public record ClearCheckCommand(Guid Id, DateTime? MovementDate = null, string? Notes = null, Guid? TreasuryAccountId = null)
    : IRequest<CheckDto>;

public class ClearCheckCommandHandler : IRequestHandler<ClearCheckCommand, CheckDto>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    private readonly IPeriodCloseService _periodClose;

    public ClearCheckCommandHandler(IApplicationDbContext db, ICurrentUserService currentUser, IPeriodCloseService periodClose)
    { _db = db; _currentUser = currentUser; _periodClose = periodClose; }

    public async Task<CheckDto> Handle(ClearCheckCommand request, CancellationToken cancellationToken)
    {
        var entity = await _db.Checks.Include(c => c.Movements)
            .FirstOrDefaultAsync(c => c.Id == request.Id, cancellationToken)
            ?? throw new NotFoundException("Check", request.Id);

        var movementDate = request.MovementDate ?? DateTime.UtcNow;
        await _periodClose.EnsureOpenAsync(movementDate, cancellationToken);

        var accountId = request.TreasuryAccountId ?? entity.TreasuryAccountId
            ?? throw new DomainException("The check must be deposited into a bank/treasury account before it can be cleared.");

        var account = await _db.TreasuryAccounts.AsNoTracking()
            .FirstOrDefaultAsync(a => a.Id == accountId, cancellationToken)
            ?? throw new NotFoundException("Treasury Account", accountId);

        if (entity.TreasuryAccountId != account.Id)
        {
            if (entity.Status is CheckStatus.Received or CheckStatus.InHand)
                entity.Deposit(account.Id, account.Name, movementDate, _currentUser.UserName);
            else
                entity.SetDrawnOnAccount(account.Id);
        }

        entity.Clear(movementDate, _currentUser.UserName, request.Notes);

        var direction = entity.Direction == CheckDirection.CustomerCheck ? TreasuryDirection.In : TreasuryDirection.Out;
        var description = entity.Direction == CheckDirection.CustomerCheck
            ? $"Cleared customer check {entity.CheckNumber} ({entity.BankName})"
            : $"Cleared supplier check {entity.CheckNumber} ({entity.BankName})";

        _db.TreasuryTransactions.Add(new TreasuryTransaction(
            account.Id, movementDate, DocumentType.CheckRegister, entity.CheckNumber, entity.Id,
            entity.Amount, direction, description, _currentUser.UserName));

        await _db.SaveChangesAsync(cancellationToken);

        var list = await CheckDtoBuilder.BuildManyAsync(_db, new List<Check> { entity }, true, cancellationToken);
        return list[0];
    }
}

public record BounceCheckCommand(Guid Id, string Reason, DateTime? MovementDate = null) : IRequest<CheckDto>;

public class BounceCheckCommandValidator : AbstractValidator<BounceCheckCommand>
{
    public BounceCheckCommandValidator() => RuleFor(x => x.Reason).NotEmpty().MaximumLength(1000);
}

public class BounceCheckCommandHandler : IRequestHandler<BounceCheckCommand, CheckDto>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    public BounceCheckCommandHandler(IApplicationDbContext db, ICurrentUserService currentUser)
    { _db = db; _currentUser = currentUser; }

    public Task<CheckDto> Handle(BounceCheckCommand request, CancellationToken cancellationToken)
        => CheckWorkflow.MutateAsync(_db, request.Id,
            entity => entity.Bounce(request.MovementDate ?? DateTime.UtcNow, _currentUser.UserName, request.Reason),
            cancellationToken);
}

/// <summary>Returns a bounced/endorsed instrument back into the company's hands, still as the same check.</summary>
public record ReturnCheckToCompanyCommand(Guid Id, string? Reason = null, DateTime? MovementDate = null) : IRequest<CheckDto>;

public class ReturnCheckToCompanyCommandHandler : IRequestHandler<ReturnCheckToCompanyCommand, CheckDto>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    public ReturnCheckToCompanyCommandHandler(IApplicationDbContext db, ICurrentUserService currentUser)
    { _db = db; _currentUser = currentUser; }

    public async Task<CheckDto> Handle(ReturnCheckToCompanyCommand request, CancellationToken cancellationToken)
    {
        var company = await CheckRules.ResolveCompanyHolderNameAsync(_db, cancellationToken);
        return await CheckWorkflow.MutateAsync(_db, request.Id,
            entity => entity.ReturnToCompany(request.MovementDate ?? DateTime.UtcNow, company, _currentUser.UserName, request.Reason),
            cancellationToken);
    }
}

public record CancelCheckCommand(Guid Id, string Reason, DateTime? MovementDate = null) : IRequest<CheckDto>;

public class CancelCheckCommandValidator : AbstractValidator<CancelCheckCommand>
{
    public CancelCheckCommandValidator() => RuleFor(x => x.Reason).NotEmpty().MaximumLength(1000);
}

public class CancelCheckCommandHandler : IRequestHandler<CancelCheckCommand, CheckDto>
{
    private readonly IApplicationDbContext _db;
    private readonly ICurrentUserService _currentUser;
    public CancelCheckCommandHandler(IApplicationDbContext db, ICurrentUserService currentUser)
    { _db = db; _currentUser = currentUser; }

    public Task<CheckDto> Handle(CancelCheckCommand request, CancellationToken cancellationToken)
        => CheckWorkflow.MutateAsync(_db, request.Id,
            entity => entity.Cancel(request.MovementDate ?? DateTime.UtcNow, _currentUser.UserName, request.Reason),
            cancellationToken);
}

internal static class CheckWorkflow
{
    public static async Task<CheckDto> MutateAsync(
        IApplicationDbContext db, Guid id, Action<Check> mutate, CancellationToken cancellationToken)
    {
        var entity = await db.Checks.Include(c => c.Movements)
            .FirstOrDefaultAsync(c => c.Id == id, cancellationToken)
            ?? throw new NotFoundException("Check", id);

        mutate(entity);
        await db.SaveChangesAsync(cancellationToken);

        var list = await CheckDtoBuilder.BuildManyAsync(db, new List<Check> { entity }, true, cancellationToken);
        return list[0];
    }
}

internal static class CheckRules
{
    /// <summary>
    /// Duplicate instrument detection (spec section 55): the same bank + number can only exist once for the
    /// same customer or supplier, so the identical physical check can never enter the register twice.
    /// </summary>
    public static async Task EnsureNotDuplicateAsync(
        IApplicationDbContext db, string bankName, string checkNumber, Guid? customerId, Guid? supplierId,
        CancellationToken cancellationToken)
    {
        var bank = bankName.Trim();
        var number = checkNumber.Trim();

        var duplicate = await db.Checks.AsNoTracking().AnyAsync(c =>
            c.BankName == bank && c.CheckNumber == number && c.CustomerId == customerId && c.SupplierId == supplierId,
            cancellationToken);

        if (duplicate)
            throw new DomainException(
                $"Check number '{number}' from '{bank}' is already registered for this party. " +
                "The same physical instrument must never be registered twice.");
    }

    /// <summary>The company's own display name, used as the holder when it holds the instrument. Falls back to a neutral label.</summary>
    public static async Task<string> ResolveCompanyHolderNameAsync(IApplicationDbContext db, CancellationToken cancellationToken)
    {
        var settings = await db.CompanySettings.AsNoTracking().FirstOrDefaultAsync(cancellationToken);
        if (settings is null) return "Company";
        return string.IsNullOrWhiteSpace(settings.CompanyNameEn) ? settings.CompanyNameAr : settings.CompanyNameEn;
    }
}
